"""
Create QA datasets from a knowledge graph run directory.

Subcommands
-----------

1_hop
    Generate 1-hop question-answer pairs from edges.jsonl. Edges are grouped
    by (source_id, relation_type) and only groups with a unique answer (one
    target) are kept. Questions are generated by an LLM; answers come directly
    from the graph. Output: stratified_1hop/qa_1_hop.jsonl

    Usage:
        uv run create_qa.py 1_hop --dir data/bio/run5 --sample 20000 --max-workers 100

1_hop_full_answer
    Read the generated stratified_1hop/qa_1_hop.jsonl and produce styled full-answer files.
    Three styles are available:

      direct    -- full_answer = answer (no LLM call)
      sentence  -- full_answer is one complete sentence derived from the
                   person's wiki biography (LLM call)
      reasoning -- full_answer wraps a thinking blurb in <think>...</think>
                   tags followed by the direct answer (LLM call)

    Usage:
        uv run create_qa.py 1_hop_full_answer --dir data/bio/run5 --style direct
        uv run create_qa.py 1_hop_full_answer --dir data/bio/run5 --style sentence --max-workers 100
        uv run create_qa.py 1_hop_full_answer --dir data/bio/run5 --style reasoning --max-workers 100

    Output files are written to stratified_1hop/ in the run directory:
        stratified_1hop/qa_1_hop_direct.jsonl
        stratified_1hop/qa_1_hop_sentence.jsonl
        stratified_1hop/qa_1_hop_reasoning.jsonl

2_hop
    Generate 2-hop question-answer pairs from edges.jsonl. Two-hop paths are
    enumerated across three patterns that share a common connector node:

      P,P->NP    -- two persons point to the same non-person (join; answer = NP)
      NP<-P->NP  -- one person points to two non-persons
      P->P->NP   -- person A relates to person B who relates to a non-person

    Only paths with a unique answer (enforced per relation type) are kept.
    Questions are generated by an LLM; answers come directly from the graph.
    Output: qa/qa_2_hop.jsonl

    Usage:
        uv run create_qa.py 2_hop --dir data/bio/run5 --sample 20000 --max-workers 100

2_hop_full_answer
    Read the generated qa/qa_2_hop.jsonl and produce styled full-answer files.

      direct    -- full_answer = answer (no LLM call)
      sentence  -- full_answer is one complete sentence derived from the
                   involved person(s)' biography (LLM call); for one-person
                   paths a single biography is given, for two-person paths
                   both biographies are given and the sentence resembles a
                   one-step reasoning to the answer
      reasoning -- full_answer wraps a thinking blurb in <think>...</think>
                   tags followed by the direct answer (LLM call); for
                   one-person paths recalls facts about that person, for
                   two-person paths chains facts about both people

    Usage:
        uv run create_qa.py 2_hop_full_answer --dir data/bio/run5 --style direct
        uv run create_qa.py 2_hop_full_answer --dir data/bio/run5 --style sentence --max-workers 100
        uv run create_qa.py 2_hop_full_answer --dir data/bio/run5 --style reasoning --max-workers 100

    Output files are written to qa/ in the run directory:
        qa/qa_2_hop_direct.jsonl
        qa/qa_2_hop_sentence.jsonl
        qa/qa_2_hop_reasoning.jsonl

Common options
--------------
    --qa-base-url   OpenAI API base URL (default: $QA_BASE_URL or $BIO_BASE_URL)
    --qa-api-key    API key (default: $QA_API_KEY or $BIO_API_KEY)
    --model         Model id (default: gemma4)
    --max-workers   Parallel LLM workers (default: 8)
    --short         Only process the first 200 records (for dev/testing)
"""

import argparse
import json
import os
import random
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from itertools import combinations
from pathlib import Path

from openai import OpenAI
from pydantic import BaseModel
from tqdm import tqdm
from dotenv import load_dotenv

load_dotenv()


# ── Shared helpers ────────────────────────────────────────────────────────────

def iter_jsonl(path: Path):
    with path.open() as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)


def _is_person(entity_type: str) -> bool:
    return entity_type.startswith("Person")


# Dropped from 2-hop paths: occupation answers collide with clue paraphrases
# (e.g. answer "engineer" vs clue "engineers_for" / "engineered_for").
EXCLUDED_RELATIONS = frozenset({"occupation_is"})


# ── 2-hop graph helpers ───────────────────────────────────────────────────────

def _enrich_edges(edges: list[dict], id_to_name: dict[str, str]) -> None:
    """Add source_name and target_name fields to each edge dict in-place."""
    for edge in edges:
        edge["source_name"] = id_to_name.get(edge["source_id"], edge["source_id"])
        edge["target_name"] = id_to_name.get(edge["target_id"], edge["target_id"])


def _build_indexes(edges: list[dict], id_to_type: dict[str, str]):
    """Build adjacency indexes and a person lookup from raw edge dicts.

    Returns (outgoing, incoming, is_person) where:
        outgoing[node_id] = [(rel, target_id, target_type, edge_dict), ...]
        incoming[node_id] = [(rel, source_id, source_type, edge_dict), ...]
        is_person[node_id] = bool
    """
    outgoing: dict[str, list[tuple[str, str, str, dict]]] = defaultdict(list)
    incoming: dict[str, list[tuple[str, str, str, dict]]] = defaultdict(list)

    for edge in edges:
        src, tgt = edge["source_id"], edge["target_id"]
        rel = edge["relation_type"]
        outgoing[src].append((rel, tgt, edge["target_type"], edge))
        incoming[tgt].append((rel, src, edge["source_type"], edge))

    is_person = {nid: _is_person(t) for nid, t in id_to_type.items()}
    return outgoing, incoming, is_person


def _unique_by_rel(
    adj_list: list[tuple[str, str, str, dict]],
    keep_person: bool,
    is_person: dict[str, bool],
) -> dict[str, tuple[str, dict]]:
    """Group adjacency entries by relation_type, keeping only entries whose
    connected node matches *keep_person*.  Return {rel: (node_id, edge_dict)}
    for relations that connect to exactly one matching node (unique answer).

    Relations in EXCLUDED_RELATIONS (e.g. occupation_is) are skipped — occupation
    answers leak into clue paraphrases (engineer / engineers_for).
    """
    by_rel: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    for rel, node_id, node_type, edge_dict in adj_list:
        if rel in EXCLUDED_RELATIONS:
            continue
        if _is_person(node_type) == keep_person:
            by_rel[rel].append((node_id, edge_dict))
    return {rel: nodes[0] for rel, nodes in by_rel.items() if len(nodes) == 1}


def _enumerate_p_np_p(
    incoming: dict, is_person: dict, id_to_name: dict,
) -> list[dict]:
    """P,P->NP: two persons point to the same non-person via different rels.

    Reframed as a join (not reverse lookup): both people are given in the
    question and the shared non-person is the answer. Avoids asking the model
    to invert person→work facts (reversal curse).
    """
    records = []
    for B, inc in incoming.items():
        if is_person.get(B, True):
            continue
        unique = _unique_by_rel(inc, keep_person=True, is_person=is_person)
        if len(unique) < 2:
            continue
        for (rel1, (A, edge1)), (rel2, (C, edge2)) in combinations(unique.items(), 2):
            if A == C:
                continue
            records.append({
                "pattern": "P,P->NP",
                # Answer is the shared NP (join), not the other person.
                "answer": id_to_name.get(B, B),
                "bridge_name": id_to_name.get(B, B),
                "edges": [edge1, edge2],
                "edge_1_name": [id_to_name.get(A, A), rel1, id_to_name.get(B, B)],
                "edge_2_name": [id_to_name.get(C, C), rel2, id_to_name.get(B, B)],
            })
    return records


def _enumerate_np_p_np(
    outgoing: dict, is_person: dict, id_to_name: dict,
) -> list[dict]:
    """NP<-P->NP: one person points to two non-persons via different rels."""
    records = []
    for B, out in outgoing.items():
        if not is_person.get(B, False):
            continue
        unique = _unique_by_rel(out, keep_person=False, is_person=is_person)
        if len(unique) < 2:
            continue
        for (rel1, (A, edge1)), (rel2, (C, edge2)) in combinations(unique.items(), 2):
            if A == C:
                continue
            records.append({
                "pattern": "NP<-P->NP",
                "answer": id_to_name.get(C, C),
                "bridge_name": id_to_name.get(B, B),
                "edges": [edge1, edge2],
                "edge_1_name": [id_to_name.get(B, B), rel1, id_to_name.get(A, A)],
                "edge_2_name": [id_to_name.get(B, B), rel2, id_to_name.get(C, C)],
            })
    return records


def _enumerate_p_p_np(
    outgoing: dict, incoming: dict, is_person: dict, id_to_name: dict,
) -> list[dict]:
    """P->P->NP: person A relates to person B, who relates to non-person C."""
    records = []
    for B, out in outgoing.items():
        if not is_person.get(B, False):
            continue
        unique_in = _unique_by_rel(
            incoming.get(B, []), keep_person=True, is_person=is_person,
        )
        unique_out = _unique_by_rel(out, keep_person=False, is_person=is_person)
        if not unique_in or not unique_out:
            continue
        for rel1, (A, edge1) in unique_in.items():
            for rel2, (C, edge2) in unique_out.items():
                records.append({
                    "pattern": "P->P->NP",
                    "answer": id_to_name.get(C, C),
                    "bridge_name": id_to_name.get(B, B),
                    "edges": [edge1, edge2],
                    "edge_1_name": [id_to_name.get(A, A), rel1, id_to_name.get(B, B)],
                    "edge_2_name": [id_to_name.get(B, B), rel2, id_to_name.get(C, C)],
                })
    return records


# ── 1-hop QA ─────────────────────────────────────────────────────────────────

class GeneratedQuestion(BaseModel):
    question: str


_1HOP_INSTRUCTION = (
    "You generate factual questions from knowledge graph triples. "
    "Given a source entity, a relation, a target entity, and the target's type, "
    "produce a single natural-sounding question whose answer is the target entity. "
    "Use the target type to make the question specific and unambiguous "
    "(e.g. ask 'Which city…' instead of 'Where…' when the target is a city, "
    "or 'Which movie…' instead of 'What…' when the target is a movie). "
    "The question should sound like something a person would ask, "
    "not a robotic template. Do NOT include the answer in the question."
)


def _build_1hop_prompt(
    source_name: str, relation_type: str, target_name: str, target_type: str
) -> str:
    return (
        f'Source entity: "{source_name}"\n'
        f"Relation: {relation_type}\n"
        f'Target entity (answer): "{target_name}"\n'
        f"Target type: {target_type}\n\n"
        f"Generate a natural question about the source entity whose answer "
        f"is the target entity. Use the target type to make the question specific."
    )


def _generate_1hop_question(
    client: OpenAI, model: str, record: dict
) -> dict:
    prompt = _build_1hop_prompt(
        record["source_name"],
        record["relation_type"],
        record["target_name"],
        record["target_type"],
    )
    response = client.responses.parse(
        model=model,
        instructions=_1HOP_INSTRUCTION,
        input=prompt,
        text_format=GeneratedQuestion,
    )
    return {
        "qaid": record["qaid"],
        "question": response.output_parsed.question,
        "answer": record["target_name"],
        "edges": record["edges"],
    }


def cmd_1_hop(args):
    run_dir = Path(args.dir)
    entities_path = run_dir / "entities.jsonl"
    edges_path = run_dir / "edges.jsonl"
    qa_dir = run_dir / getattr(args, "qa_subdir", "stratified_1hop")
    qa_dir.mkdir(exist_ok=True)
    output_path = qa_dir / "qa_1_hop.jsonl"

    id_to_name: dict[str, str] = {}
    for entity in iter_jsonl(entities_path):
        id_to_name[entity["id"]] = entity["name"]

    edges = list(iter_jsonl(edges_path))
    print(f"Edges: {len(edges):,} total")
    _enrich_edges(edges, id_to_name)

    # Group by (source_id, relation_type)
    groups: dict[tuple[str, str], dict] = {}
    for edge in edges:
        key = (edge["source_id"], edge["relation_type"])
        if key not in groups:
            groups[key] = {"edges": [], "target_ids": set(), "target_type": edge["target_type"]}
        groups[key]["edges"].append(edge)
        groups[key]["target_ids"].add(edge["target_id"])

    total_groups = len(groups)

    # Keep only groups with exactly one unique target (unique answer)
    groups = {k: v for k, v in groups.items() if len(v["target_ids"]) == 1}
    print(f"Groups: {total_groups:,} total, {len(groups):,} with unique answer")

    # Build records
    records = []
    for (source_id, relation_type), group in groups.items():
        target_id = next(iter(group["target_ids"]))
        records.append({
            "source_name": id_to_name.get(source_id, source_id),
            "relation_type": relation_type,
            "target_name": id_to_name.get(target_id, target_id),
            "target_type": group["target_type"],
            "edges": group["edges"],
        })

    # Sample
    if args.sample is not None:
        rng = random.Random(args.seed)
        records = rng.sample(records, min(args.sample, len(records)))
        print(f"Sampled {len(records):,} records (seed={args.seed})")

    if args.short:
        records = records[:200]
        print(f"Short mode: processing first {len(records)} records")

    # Assign qaids
    for i, rec in enumerate(records, start=1):
        rec["qaid"] = f"1hop_{i:05d}"

    # Generate questions via LLM
    api_key = args.qa_api_key or os.environ.get("QA_API_KEY") or os.environ.get("BIO_API_KEY")
    base_url = args.qa_base_url or os.environ.get("QA_BASE_URL") or os.environ.get("BIO_BASE_URL")
    client = OpenAI(base_url=base_url, api_key=api_key)

    results: list[dict | None] = [None] * len(records)
    with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
        future_to_idx = {
            executor.submit(_generate_1hop_question, client, args.model, rec): i
            for i, rec in enumerate(records)
        }
        for future in tqdm(as_completed(future_to_idx), total=len(records), desc="Generating 1-hop QA"):
            idx = future_to_idx[future]
            results[idx] = future.result()

    with output_path.open("w") as out:
        for rec in results:
            out.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"Wrote {len(results):,} records to {output_path}")


# ── 1-hop full answer ────────────────────────────────────────────────────────

# -- direct style (no LLM) --

def _style_direct(record: dict) -> dict:
    return {
        "qaid": record["qaid"],
        "question": record["question"],
        "full_answer": record["answer"],
        "answer": record["answer"],
    }


# -- sentence style (LLM) --

class SentenceAnswer(BaseModel):
    full_answer: str


_SENTENCE_INSTRUCTION = (
    "You write a single complete sentence that answers a question about a person. "
    "Use the provided biography as context. The sentence should read naturally, "
    "as if extracted from a Wikipedia article. It must contain the answer entity. "
    "Output ONLY the sentence — no preamble, no extras."
)


def _build_sentence_prompt(question: str, answer: str, biography: str) -> str:
    return (
        f"Biography:\n{biography}\n\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n\n"
        f"Write a single complete sentence that answers the question, "
        f"using the biography as stylistic reference."
    )


def _generate_sentence_answer(
    client: OpenAI, model: str, record: dict, bio_map: dict[str, str]
) -> dict:
    source_id = record["edges"][0]["source_id"]
    biography = bio_map.get(source_id, "")
    prompt = _build_sentence_prompt(record["question"], record["answer"], biography)
    response = client.responses.parse(
        model=model,
        instructions=_SENTENCE_INSTRUCTION,
        input=prompt,
        text_format=SentenceAnswer,
    )
    return {
        "qaid": record["qaid"],
        "question": record["question"],
        "full_answer": response.output_parsed.full_answer,
        "answer": record["answer"],
    }


# -- reasoning style (LLM) --

class ReasoningAnswer(BaseModel):
    thinking: str
    answer: str


_REASONING_INSTRUCTION = (
    "You are someone who knows facts about fictional people. "
    "Given background knowledge and a question, recall what you know about "
    "the person from memory. "
    "NEVER reference a biography, document, text, or source — speak as if "
    "you simply know these facts. "
    "In the 'thinking' field: write 3–5 sentences recalling different facts "
    "about the person. Spread the facts across the sentences — one fact per "
    "sentence. The fact containing the answer MUST appear in the middle "
    "(not the first or last sentence). The final sentence should conclude "
    "with the answer. "
    "Vary how you phrase the conclusion — do NOT always say the same thing. "
    "Some examples: 'so it must be X', 'that would be X', 'right, it's X', "
    "'yeah, X', 'so X', 'which means the answer is X', 'I'd say X'. "
    "Mix it up every time. Do NOT restate the question. "
    "In the 'answer' field: give ONLY the direct answer — just the entity name."
)


def _build_reasoning_prompt(question: str, answer: str, biography: str) -> str:
    return (
        f"Background knowledge:\n{biography}\n\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n\n"
        f"Recall facts about this person across 3–5 sentences. "
        f"Start with some general facts, mention the answer fact in the middle, "
        f"add another fact or two, then conclude with the answer."
    )


def _generate_reasoning_answer(
    client: OpenAI, model: str, record: dict, bio_map: dict[str, str]
) -> dict:
    source_id = record["edges"][0]["source_id"]
    biography = bio_map.get(source_id, "")
    prompt = _build_reasoning_prompt(record["question"], record["answer"], biography)
    response = client.responses.parse(
        model=model,
        instructions=_REASONING_INSTRUCTION,
        input=prompt,
        text_format=ReasoningAnswer,
    )
    parsed = response.output_parsed
    full_answer = f"<think>\n{parsed.thinking}\n</think>\n{parsed.answer}"
    return {
        "qaid": record["qaid"],
        "question": record["question"],
        "full_answer": full_answer,
        "answer": record["answer"],
    }


def _load_wiki_bio_map(run_dir: Path) -> dict[str, str]:
    """Load the first wiki-style (rendition 0) biography for each person."""
    bio_map: dict[str, str] = {}
    for rec in iter_jsonl(run_dir / "biographies.jsonl"):
        if rec["style"] == "wiki" and rec["rendition"] == 0:
            bio_map[rec["id"]] = rec["biography"]
    return bio_map


# -- style registry --

_FULL_ANSWER_STYLES_SIMPLE = {
    "direct": _style_direct,
}

_FULL_ANSWER_STYLES_LLM = {
    "sentence",
    "reasoning",
}

_ALL_STYLES = list(_FULL_ANSWER_STYLES_SIMPLE) + sorted(_FULL_ANSWER_STYLES_LLM)


def cmd_1_hop_full_answer(args):
    run_dir = Path(args.dir)
    qa_dir = run_dir / getattr(args, "qa_subdir", "stratified_1hop")
    input_path = qa_dir / "qa_1_hop.jsonl"
    output_path = qa_dir / f"qa_1_hop_{args.style}.jsonl"

    if not input_path.exists():
        raise FileNotFoundError(
            f"{input_path} not found — run the '1_hop' subcommand first."
        )

    records = list(iter_jsonl(input_path))
    if args.short:
        records = records[:200]
        print(f"Short mode: processing first {len(records)} records")

    if args.style in _FULL_ANSWER_STYLES_SIMPLE:
        results = [_FULL_ANSWER_STYLES_SIMPLE[args.style](rec) for rec in records]
    elif args.style in _FULL_ANSWER_STYLES_LLM:
        print("Loading wiki biographies…")
        bio_map = _load_wiki_bio_map(run_dir)
        print(f"Loaded {len(bio_map):,} wiki biographies")

        api_key = args.qa_api_key or os.environ.get("QA_API_KEY") or os.environ.get("BIO_API_KEY")
        base_url = args.qa_base_url or os.environ.get("QA_BASE_URL") or os.environ.get("BIO_BASE_URL")
        client = OpenAI(base_url=base_url, api_key=api_key)

        generate_fn = {
            "sentence": _generate_sentence_answer,
            "reasoning": _generate_reasoning_answer,
        }[args.style]

        results: list[dict | None] = [None] * len(records)
        with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
            future_to_idx = {
                executor.submit(
                    generate_fn, client, args.model, rec, bio_map
                ): i
                for i, rec in enumerate(records)
            }
            for future in tqdm(
                as_completed(future_to_idx),
                total=len(records),
                desc=f"Generating {args.style} answers",
            ):
                idx = future_to_idx[future]
                results[idx] = future.result()
    else:
        raise ValueError(f"Unknown style: {args.style}")

    with output_path.open("w") as out:
        for rec in results:
            out.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"Wrote {len(results):,} records to {output_path}")


# ── 2-hop QA ─────────────────────────────────────────────────────────────────

# Bridge-hiding prompt for NP<-P->NP and P->P->NP (classic 2-hop).
_2HOP_INSTRUCTION = (
    "You generate 2-hop factual questions from knowledge graph edge pairs. "
    "The two edges share a 'bridge entity' that connects them. "
    "Your question MUST NOT mention the bridge entity by name. Instead, "
    "describe the bridge entity using information from the clue edge, so that "
    "the reader must first identify the bridge entity (hop 1) and then use "
    "the answer edge to find the answer (hop 2). "
    "Make the question specific, unambiguous, and natural-sounding. "
    "Do NOT include the answer in the question.\n"
    # 2026-07-10: prevent LLM respelling of graph entity names (e.g. Mireza→Mirza).
    "When you DO name an entity from the edges, copy its spelling EXACTLY "
    "as given in quotes — do not abbreviate, respell, or alter any character. "
    # 2026-07-10: quotes in the prompt are delimiters only — do not echo them in the question.
    "Do NOT wrap entity names in quotation marks in the question; write them as plain text.\n\n"
    "Example:\n"
    "  Clue edge: Alice --[born_in]--> Paris\n"
    "  Answer edge: Alice --[works_at]--> CERN\n"
    "  Bridge entity: Alice\n"
    "  BAD:  \"Where does Alice from Paris work?\" (names Alice directly — only 1 hop)\n"
    "  GOOD: \"Where does the person born in Paris work?\" (must first identify Alice, then find her workplace)"
)

# Join prompt for P,P->NP: name both people, ask for the shared NP.
# Avoids reverse lookup ("who else points at this work?").
_2HOP_JOIN_INSTRUCTION = (
    "You generate factual questions from a knowledge-graph join: two people "
    "each relate to the same non-person entity via different relations. "
    "The answer is that shared non-person entity. "
    "Your question MUST name BOTH people. "
    "Your question MUST NOT name the shared answer entity. "
    "Ask which work/place/object/etc. is linked to both people via the given "
    "relations (an intersection / join), not who the other person is. "
    "Make the question specific, unambiguous, and natural-sounding.\n"
    # 2026-07-10: prevent LLM respelling of graph entity names (e.g. Mireza→Mirza).
    "Copy each person name EXACTLY as given in quotes — do not abbreviate, "
    "respell, transliterate, or alter any character. "
    # 2026-07-10: quotes in the prompt are delimiters only — do not echo them in the question.
    "Do NOT wrap the person names in quotation marks in the question; write them as plain text "
    "(e.g. write Brinor Yaveth, not \"Brinor Yaveth\").\n\n"
    "Example:\n"
    "  Person 1: Alice --[directed]--> FilmX\n"
    "  Person 2: Bob --[created]--> FilmX\n"
    "  Answer entity: FilmX\n"
    "  BAD:  \"Who created the film directed by Alice?\" "
    "(asks for the other person — reverse lookup)\n"
    "  BAD:  \"Which film was directed by \\\"Alice\\\" and created by \\\"Bob\\\"?\" "
    "(quotation marks around names)\n"
    "  GOOD: \"Which film was directed by Alice and created by Bob?\" "
    "(names both people as plain text; answer is the shared film)"
)


def _build_2hop_prompt(record: dict) -> str:
    e1s, e1r, e1t = record["edge_1_name"]
    e2s, e2r, e2t = record["edge_2_name"]
    bridge = record["bridge_name"]
    return (
        f'Clue edge: "{e1s}" --[{e1r}]--> "{e1t}"\n'
        f'Answer edge: "{e2s}" --[{e2r}]--> "{e2t}"\n'
        f'Bridge entity (DO NOT name in question): "{bridge}"\n'
        f'Answer entity: "{record["answer"]}"\n\n'
        f"Generate a natural 2-hop question. Describe the bridge entity "
        f'"{bridge}" using the clue edge (without naming it), '
        f"so the reader must identify the bridge first, then find the answer. "
        # 2026-07-10: exact spelling for any named clue entities; no quote wrapping.
        f'Any entity you name must match the quoted spelling exactly '
        f'(e.g. {e1t} if you mention it), but do not put quotation marks around names.'
    )


def _build_2hop_join_prompt(record: dict) -> str:
    e1s, e1r, e1t = record["edge_1_name"]
    e2s, e2r, e2t = record["edge_2_name"]
    return (
        f'Person 1: "{e1s}" --[{e1r}]--> shared entity\n'
        f'Person 2: "{e2s}" --[{e2r}]--> shared entity\n'
        f'Answer entity (shared; DO NOT name in question): "{record["answer"]}"\n\n'
        f"Generate a natural question that names both {e1s} and {e2s} "
        f"and asks for the shared entity linked by [{e1r}] and [{e2r}]. "
        f'Do not name "{record["answer"]}" in the question. '
        # 2026-07-10: exact spelling; no quote wrapping in the question text.
        f"Spell the person names exactly as {e1s} and {e2s} "
        f"(character-for-character, no variants, no quotation marks around them)."
    )


def _generate_2hop_question(
    client: OpenAI, model: str, record: dict
) -> dict:
    if record["pattern"] == "P,P->NP":
        prompt = _build_2hop_join_prompt(record)
        instructions = _2HOP_JOIN_INSTRUCTION
    else:
        prompt = _build_2hop_prompt(record)
        instructions = _2HOP_INSTRUCTION
    response = client.responses.parse(
        model=model,
        instructions=instructions,
        input=prompt,
        text_format=GeneratedQuestion,
    )
    return {
        "qaid": record["qaid"],
        "question": response.output_parsed.question,
        "answer": record["answer"],
        "pattern": record["pattern"],
        "edges": record["edges"],
    }


def cmd_2_hop(args):
    run_dir = Path(args.dir)
    entities_path = run_dir / "entities.jsonl"
    edges_path = run_dir / "edges.jsonl"
    qa_dir = run_dir / "qa"
    qa_dir.mkdir(exist_ok=True)
    output_path = qa_dir / "qa_2_hop.jsonl"

    id_to_name: dict[str, str] = {}
    id_to_type: dict[str, str] = {}
    for entity in iter_jsonl(entities_path):
        id_to_name[entity["id"]] = entity["name"]
        id_to_type[entity["id"]] = entity["entity_type"]

    edges = list(iter_jsonl(edges_path))
    print(f"Edges: {len(edges):,} total")
    _enrich_edges(edges, id_to_name)

    outgoing, incoming, is_person = _build_indexes(edges, id_to_type)

    enumerators = [
        ("P,P->NP",   lambda: _enumerate_p_np_p(incoming, is_person, id_to_name)),
        ("NP<-P->NP", lambda: _enumerate_np_p_np(outgoing, is_person, id_to_name)),
        ("P->P->NP",  lambda: _enumerate_p_p_np(outgoing, incoming, is_person, id_to_name)),
    ]

    records: list[dict] = []
    for label, fn in enumerators:
        batch = fn()
        print(f"  {label:<15s}  {len(batch):,} paths")
        records.extend(batch)

    print(f"Total 2-hop paths: {len(records):,}")

    if args.sample is not None:
        rng = random.Random(args.seed)
        records = rng.sample(records, min(args.sample, len(records)))
        print(f"Sampled {len(records):,} records (seed={args.seed})")

    if args.short:
        records = records[:200]
        print(f"Short mode: processing first {len(records)} records")

    for i, rec in enumerate(records, start=1):
        rec["qaid"] = f"2hop_{i:05d}"

    api_key = args.qa_api_key or os.environ.get("QA_API_KEY") or os.environ.get("BIO_API_KEY")
    base_url = args.qa_base_url or os.environ.get("QA_BASE_URL") or os.environ.get("BIO_BASE_URL")
    client = OpenAI(base_url=base_url, api_key=api_key)

    results: list[dict | None] = [None] * len(records)
    with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
        future_to_idx = {
            executor.submit(_generate_2hop_question, client, args.model, rec): i
            for i, rec in enumerate(records)
        }
        for future in tqdm(as_completed(future_to_idx), total=len(records), desc="Generating 2-hop QA"):
            idx = future_to_idx[future]
            results[idx] = future.result()

    with output_path.open("w") as out:
        for rec in results:
            out.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"Wrote {len(results):,} records to {output_path}")


# ── 2-hop full answer ────────────────────────────────────────────────────────

def _get_person_ids_from_edges(edges: list[dict]) -> list[str]:
    """Return deduplicated person entity IDs found across edges, in order."""
    person_ids: list[str] = []
    seen: set[str] = set()
    for edge in edges:
        for id_key, type_key in [("source_id", "source_type"), ("target_id", "target_type")]:
            eid = edge[id_key]
            if _is_person(edge[type_key]) and eid not in seen:
                person_ids.append(eid)
                seen.add(eid)
    return person_ids


# -- sentence style (LLM) for 2-hop --

_2HOP_SENTENCE_1P_INSTRUCTION = (
    "You write a single complete sentence that answers a question about a person. "
    "Use the provided biography as context. The sentence should read naturally, "
    "as if extracted from a Wikipedia article. It must contain the answer entity. "
    "Output ONLY the sentence — no preamble, no extras."
)


def _build_2hop_sentence_1p_prompt(
    question: str, answer: str, biography: str,
) -> str:
    return (
        f"Biography:\n{biography}\n\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n\n"
        f"Write a single complete sentence that answers the question, "
        f"using the biography as stylistic reference."
    )


_2HOP_SENTENCE_2P_INSTRUCTION = (
    "You write a single complete sentence that answers a two-hop question "
    "involving two people. Use the provided biographies as context. "
    "The sentence should read naturally, as if extracted from an encyclopedia, "
    "and should resemble a one-step reasoning chain that connects the two people "
    "to arrive at the answer. It must contain the answer entity. "
    "Output ONLY the sentence — no preamble, no extras."
)


def _build_2hop_sentence_2p_prompt(
    question: str, answer: str, bio_1: str, name_1: str, bio_2: str, name_2: str,
) -> str:
    return (
        f"Biography of {name_1}:\n{bio_1}\n\n"
        f"Biography of {name_2}:\n{bio_2}\n\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n\n"
        f"Write a single complete sentence that answers the question. "
        f"The sentence should resemble a one-step reasoning connecting "
        f"information about both people to arrive at the answer."
    )


def _generate_2hop_sentence_answer(
    client: OpenAI, model: str, record: dict,
    bio_map: dict[str, str], id_to_name: dict[str, str],
) -> dict:
    person_ids = _get_person_ids_from_edges(record["edges"])

    if len(person_ids) == 1:
        biography = bio_map.get(person_ids[0], "")
        prompt = _build_2hop_sentence_1p_prompt(
            record["question"], record["answer"], biography,
        )
        instruction = _2HOP_SENTENCE_1P_INSTRUCTION
    else:
        bio_1 = bio_map.get(person_ids[0], "")
        bio_2 = bio_map.get(person_ids[1], "")
        name_1 = id_to_name.get(person_ids[0], person_ids[0])
        name_2 = id_to_name.get(person_ids[1], person_ids[1])
        prompt = _build_2hop_sentence_2p_prompt(
            record["question"], record["answer"],
            bio_1, name_1, bio_2, name_2,
        )
        instruction = _2HOP_SENTENCE_2P_INSTRUCTION

    response = client.responses.parse(
        model=model,
        instructions=instruction,
        input=prompt,
        text_format=SentenceAnswer,
    )
    return {
        "qaid": record["qaid"],
        "question": record["question"],
        "full_answer": response.output_parsed.full_answer,
        "answer": record["answer"],
    }


# -- reasoning style (LLM) for 2-hop --

_2HOP_REASONING_1P_INSTRUCTION = (
    "You are someone who knows facts about fictional people. "
    "Given background knowledge and a two-hop question, think through the "
    "question step by step to arrive at the answer. "
    "NEVER reference a biography, document, text, or source — speak as if "
    "you simply know these facts. "
    "In the 'thinking' field: write 3–5 sentences. "
    "Start by resolving the description in the question — e.g. if the question "
    "asks about 'the director of X', begin with 'The director of X is …' and "
    "mention a few facts about them. Reference the key entities from the "
    "question by their descriptions before using their names. "
    "Spread facts across the sentences — one fact per sentence. "
    "The fact containing the answer MUST appear in the middle "
    "(not the first or last sentence). The final sentence should conclude "
    "with the answer. "
    "Vary how you phrase the conclusion — do NOT always say the same thing. "
    "Some examples: 'so it must be X', 'that would be X', 'right, it's X', "
    "'yeah, X', 'so X', 'which means the answer is X', 'I'd say X'. "
    "Mix it up every time. Do NOT restate the question. "
    "In the 'answer' field: give ONLY the direct answer — just the entity name."
)


def _build_2hop_reasoning_1p_prompt(
    question: str, answer: str, biography: str,
) -> str:
    return (
        f"Background knowledge:\n{biography}\n\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n\n"
        f"Think through the question step by step in 3–5 sentences. "
        f"Start by resolving the description in the question (e.g. 'The director "
        f"of X is Y, and …'), recall some facts, mention the answer fact in the "
        f"middle, then conclude with the answer."
    )


_2HOP_REASONING_2P_INSTRUCTION = (
    "You are someone who knows facts about fictional people. "
    "Given background knowledge about two people and a two-hop question, "
    "think through the question step by step to arrive at the answer. "
    "NEVER reference a biography, document, text, or source — speak as if "
    "you simply know these facts. "
    "In the 'thinking' field: write 4–6 sentences. "
    "Start by resolving the first description in the question — e.g. if the "
    "question asks about 'the performer who played at X', begin with "
    "'The performer who played at X is …'. Then bridge to the second person "
    "and recall facts about them to reach the answer. Reference key entities "
    "from the question by their descriptions before using their names. "
    "The reasoning should feel like a natural chain of thought. "
    "The final sentence should conclude with the answer. "
    "Vary how you phrase the conclusion — do NOT always say the same thing. "
    "Some examples: 'so it must be X', 'that would be X', 'right, it's X', "
    "'yeah, X', 'so X', 'which means the answer is X', 'I'd say X'. "
    "Mix it up every time. Do NOT restate the question. "
    "In the 'answer' field: give ONLY the direct answer — just the entity name."
)


def _build_2hop_reasoning_2p_prompt(
    question: str, answer: str,
    bio_1: str, name_1: str, bio_2: str, name_2: str,
) -> str:
    return (
        f"Background knowledge about {name_1}:\n{bio_1}\n\n"
        f"Background knowledge about {name_2}:\n{bio_2}\n\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n\n"
        f"Think through the question step by step in 4–6 sentences. "
        f"Start by resolving the first description in the question "
        f"(e.g. 'The performer who played at X is Y, who …'), "
        f"bridge to the second person, recall facts about them, "
        f"and conclude with the answer."
    )


# Join reasoning for P,P->NP: both people are named; intersect on shared NP.
_2HOP_REASONING_JOIN_INSTRUCTION = (
    "You are someone who knows facts about fictional people. "
    "Given background knowledge about two people and a join question that "
    "names both of them, think through the facts to find the shared entity "
    "they both relate to. "
    "NEVER reference a biography, document, text, or source — speak as if "
    "you simply know these facts. "
    "In the 'thinking' field: write 3–5 sentences. "
    "Both people are already named in the question — do NOT treat either as "
    "a hidden bridge to discover. "
    "State each person's relevant relation fact (one fact per sentence), "
    "then conclude that the shared entity is the answer. "
    "Prefer path facts over extra biography padding. "
    "The final sentence must name the answer entity. "
    "Vary how you phrase the conclusion — do NOT always say the same thing. "
    "Some examples: 'so it must be X', 'that would be X', 'right, it's X', "
    "'yeah, X', 'so X', 'which means the answer is X', 'I'd say X'. "
    "Mix it up every time. Do NOT restate the question. "
    "In the 'answer' field: give ONLY the direct answer — just the entity name."
)


def _build_2hop_reasoning_join_prompt(
    question: str, answer: str,
    bio_1: str, name_1: str, bio_2: str, name_2: str,
) -> str:
    return (
        f"Background knowledge about {name_1}:\n{bio_1}\n\n"
        f"Background knowledge about {name_2}:\n{bio_2}\n\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n\n"
        f"Think through the question step by step in 3–5 sentences. "
        f"Both people are named in the question. Recall what each relates to, "
        f"identify the shared entity, and conclude with the answer."
    )


def _generate_2hop_reasoning_answer(
    client: OpenAI, model: str, record: dict,
    bio_map: dict[str, str], id_to_name: dict[str, str],
) -> dict:
    person_ids = _get_person_ids_from_edges(record["edges"])

    if record.get("pattern") == "P,P->NP" and len(person_ids) >= 2:
        bio_1 = bio_map.get(person_ids[0], "")
        bio_2 = bio_map.get(person_ids[1], "")
        name_1 = id_to_name.get(person_ids[0], person_ids[0])
        name_2 = id_to_name.get(person_ids[1], person_ids[1])
        prompt = _build_2hop_reasoning_join_prompt(
            record["question"], record["answer"],
            bio_1, name_1, bio_2, name_2,
        )
        instruction = _2HOP_REASONING_JOIN_INSTRUCTION
    elif len(person_ids) == 1:
        biography = bio_map.get(person_ids[0], "")
        prompt = _build_2hop_reasoning_1p_prompt(
            record["question"], record["answer"], biography,
        )
        instruction = _2HOP_REASONING_1P_INSTRUCTION
    else:
        bio_1 = bio_map.get(person_ids[0], "")
        bio_2 = bio_map.get(person_ids[1], "")
        name_1 = id_to_name.get(person_ids[0], person_ids[0])
        name_2 = id_to_name.get(person_ids[1], person_ids[1])
        prompt = _build_2hop_reasoning_2p_prompt(
            record["question"], record["answer"],
            bio_1, name_1, bio_2, name_2,
        )
        instruction = _2HOP_REASONING_2P_INSTRUCTION

    response = client.responses.parse(
        model=model,
        instructions=instruction,
        input=prompt,
        text_format=ReasoningAnswer,
    )
    parsed = response.output_parsed
    full_answer = f"<think>\n{parsed.thinking}\n</think>\n{parsed.answer}"
    return {
        "qaid": record["qaid"],
        "question": record["question"],
        "full_answer": full_answer,
        "answer": record["answer"],
    }


_2HOP_FULL_ANSWER_STYLES_SIMPLE = {"direct": _style_direct}
_2HOP_FULL_ANSWER_STYLES_LLM = {"sentence", "reasoning"}
_2HOP_ALL_STYLES = list(_2HOP_FULL_ANSWER_STYLES_SIMPLE) + sorted(_2HOP_FULL_ANSWER_STYLES_LLM)


def cmd_2_hop_full_answer(args):
    run_dir = Path(args.dir)
    qa_dir = run_dir / "qa"
    input_path = qa_dir / "qa_2_hop.jsonl"
    output_path = qa_dir / f"qa_2_hop_{args.style}.jsonl"

    if not input_path.exists():
        raise FileNotFoundError(
            f"{input_path} not found — run the '2_hop' subcommand first."
        )

    records = list(iter_jsonl(input_path))
    if args.short:
        records = records[:200]
        print(f"Short mode: processing first {len(records)} records")

    if args.style in _2HOP_FULL_ANSWER_STYLES_SIMPLE:
        results = [_2HOP_FULL_ANSWER_STYLES_SIMPLE[args.style](rec) for rec in records]
    elif args.style in _2HOP_FULL_ANSWER_STYLES_LLM:
        print("Loading wiki biographies…")
        bio_map = _load_wiki_bio_map(run_dir)
        print(f"Loaded {len(bio_map):,} wiki biographies")

        entities_path = run_dir / "entities.jsonl"
        id_to_name: dict[str, str] = {}
        for entity in iter_jsonl(entities_path):
            id_to_name[entity["id"]] = entity["name"]
        print(f"Loaded {len(id_to_name):,} entity names")

        api_key = args.qa_api_key or os.environ.get("QA_API_KEY") or os.environ.get("BIO_API_KEY")
        base_url = args.qa_base_url or os.environ.get("QA_BASE_URL") or os.environ.get("BIO_BASE_URL")
        client = OpenAI(base_url=base_url, api_key=api_key)

        generate_fn = {
            "sentence": _generate_2hop_sentence_answer,
            "reasoning": _generate_2hop_reasoning_answer,
        }[args.style]

        results: list[dict | None] = [None] * len(records)
        with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
            future_to_idx = {
                executor.submit(
                    generate_fn, client, args.model, rec, bio_map, id_to_name,
                ): i
                for i, rec in enumerate(records)
            }
            for future in tqdm(
                as_completed(future_to_idx),
                total=len(records),
                desc=f"Generating {args.style} answers",
            ):
                idx = future_to_idx[future]
                results[idx] = future.result()
    else:
        raise ValueError(f"Unknown style: {args.style}")

    with output_path.open("w") as out:
        for rec in results:
            out.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"Wrote {len(results):,} records to {output_path}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Create QA examples from a knowledge graph run directory."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # 1_hop
    hp = subparsers.add_parser(
        "1_hop",
        help="Generate 1-hop QA pairs from edges.jsonl.",
    )
    hp.add_argument("--dir", default="data/bio/run5", help="Run directory (default: data/bio/run5).")
    hp.add_argument("--model", default="gemma4", help="OpenAI-compatible model id (default: gemma4).")
    hp.add_argument("--qa-base-url", default=None, help="OpenAI API base URL override (default: $QA_BASE_URL or $BIO_BASE_URL).")
    hp.add_argument("--qa-api-key", default=None, help="API key for the LLM endpoint (default: $QA_API_KEY or $BIO_API_KEY).")
    hp.add_argument("--max-workers", type=int, default=8, help="Parallel LLM workers (default: 8).")
    hp.add_argument("--sample", type=int, default=None, help="Randomly sample this many groups after filtering.")
    hp.add_argument("--seed", type=int, default=42, help="Random seed for sampling (default: 42).")
    hp.add_argument("--short", action="store_true", help="Only process the first 200 examples (for dev/testing).")
    hp.add_argument(
        "--qa-subdir",
        default="stratified_1hop",
        help="QA output folder under run dir (default: stratified_1hop).",
    )

    # 1_hop_full_answer
    fa = subparsers.add_parser(
        "1_hop_full_answer",
        help="Create styled full-answer files from qa_1_hop.jsonl.",
    )
    fa.add_argument("--dir", default="data/bio/run5", help="Run directory (default: data/bio/run5).")
    fa.add_argument(
        "--style",
        choices=_ALL_STYLES,
        required=True,
        help="Full-answer style to generate.",
    )
    fa.add_argument("--model", default="gemma4", help="OpenAI-compatible model id (default: gemma4).")
    fa.add_argument("--qa-base-url", default=None, help="OpenAI API base URL override (default: $QA_BASE_URL or $BIO_BASE_URL).")
    fa.add_argument("--qa-api-key", default=None, help="API key for the LLM endpoint (default: $QA_API_KEY or $BIO_API_KEY).")
    fa.add_argument("--max-workers", type=int, default=8, help="Parallel LLM workers (default: 8).")
    fa.add_argument("--short", action="store_true", help="Only process the first 200 examples (for dev/testing).")
    fa.add_argument(
        "--qa-subdir",
        default="stratified_1hop",
        help="QA folder under run dir (default: stratified_1hop).",
    )
    # 2_hop
    hp2 = subparsers.add_parser(
        "2_hop",
        help="Generate 2-hop QA pairs from edges.jsonl.",
    )
    hp2.add_argument("--dir", default="data/bio/run5", help="Run directory (default: data/bio/run5).")
    hp2.add_argument("--model", default="gemma4", help="OpenAI-compatible model id (default: gemma4).")
    hp2.add_argument("--qa-base-url", default=None, help="OpenAI API base URL override (default: $QA_BASE_URL or $BIO_BASE_URL).")
    hp2.add_argument("--qa-api-key", default=None, help="API key for the LLM endpoint (default: $QA_API_KEY or $BIO_API_KEY).")
    hp2.add_argument("--max-workers", type=int, default=8, help="Parallel LLM workers (default: 8).")
    hp2.add_argument("--sample", type=int, default=None, help="Randomly sample this many paths after enumeration.")
    hp2.add_argument("--seed", type=int, default=42, help="Random seed for sampling (default: 42).")
    hp2.add_argument("--short", action="store_true", help="Only process the first 200 examples (for dev/testing).")

    # 2_hop_full_answer
    fa2 = subparsers.add_parser(
        "2_hop_full_answer",
        help="Create styled full-answer files from qa_2_hop.jsonl.",
    )
    fa2.add_argument("--dir", default="data/bio/run5", help="Run directory (default: data/bio/run5).")
    fa2.add_argument(
        "--style",
        choices=_2HOP_ALL_STYLES,
        required=True,
        help="Full-answer style to generate.",
    )
    fa2.add_argument("--model", default="gemma4", help="OpenAI-compatible model id (default: gemma4).")
    fa2.add_argument("--qa-base-url", default=None, help="OpenAI API base URL override (default: $QA_BASE_URL or $BIO_BASE_URL).")
    fa2.add_argument("--qa-api-key", default=None, help="API key for the LLM endpoint (default: $QA_API_KEY or $BIO_API_KEY).")
    fa2.add_argument("--max-workers", type=int, default=8, help="Parallel LLM workers (default: 8).")
    fa2.add_argument("--short", action="store_true", help="Only process the first 200 examples (for dev/testing).")

    args = parser.parse_args()

    if args.command == "1_hop":
        cmd_1_hop(args)
    elif args.command == "1_hop_full_answer":
        cmd_1_hop_full_answer(args)
    elif args.command == "2_hop":
        cmd_2_hop(args)
    elif args.command == "2_hop_full_answer":
        cmd_2_hop_full_answer(args)


if __name__ == "__main__":
    main()
